### ISSUE TITLE
vanishingly minor: example outputs are pprint not print? 

### ISSUE THREAD

**Issue by bodacea** [cage-challenge/cage-challenge-4#5]
really not an issue, but just a note for anyone following the code examples slavishly: the example outputs in https://github.com/cage-challenge/cage-challenge-4/blob/main/documentation/docs/pages/tutorials/01_Getting_Started/2_Getting_Started.md look like they've been prettyprinted (or are from a notebook?  I think that might prettyprint).  Could suggest using "from pprint import pprint; pprint(thing)" to get a cleaner format, or could just ignore this as not important.

**Comment by rykrr** [comment]
Hi there!

I used `from rich import print` to produce the output, but didn’t include it since it’d add a dependency. That being said, you have raised a good point: this could throw off someone following the documentation since the format is different, even if the content is the same. I will fix this (and the number of agents listed on the homepage) once I have a spare minute.

Thank you!
